### ISSUE TITLE
Any issues?

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#280]
Just trying to find out if anyone using the flow meter code has discovered any issues with it to this point  or noticed anything that needs to be fixed or cleaned up.

**Comment by Boombrewer** [comment]
I haven't seen anything besides the stuff we've already fixed.  I'm actually really impressed on how well its running (you did awesome).  I was planning on doing the whole update procedure tonight (if I can stay awake / sober) to see how the whole procedure goes.

**Comment by Boombrewer** [comment]
Just went through the upgrade procedure (and read through the others again) and it all looks good.  I think the release should go really well.  And I think the code is working pretty well!  Everyone is going to be so happy!

**Comment by day-trippr** [comment]
I've run through the "Upgrade" procedure to where I need a release to install :)

Here are some notes on issues I ran into along the way.

Step 2: phpmyadmin is not found, though it is installed (root is at /usr/share/phpmyadmin)

Actually a pretty common issue for some reason, can be cured by creating a symbolic link in /var/www pointing to the phpmyadmin root folder, thusly:

cd /var/www
ln -s /usr/share/phpmyadmin  [<= corrected typo for posterity sake]

This was a problem with both of my RPi systems, which were built in late April (though the dev system  had been package-upgraded within the last month).

Step 8: install packages for flow meter support

The get failed with about a half-dozen 404s.
This was resolved by doing a full package update/upgrade and re-executing the failed get.

I recommend the upgrade procedure actually start with an apt-get update && apt-get upgrade as it's almost certainly going to eliminate a bunch of get issues for folks that have been around the block with 'Pints since the V1 release and might not have been keeping their RPi's up to date.

Step 11: Thanks for changing this from a nuke command to a selective delete. BrewPi users (and possibly other package users) will never know the bullet they dodged ;) 

I do think it would be helpful to warn the upgrader that if she has modified any of the 'Pints files that this would be a good time to create a backup before executing Step 11. I've diddled the style.css, index.php and icons and images, and I'm sure I'm not alone.

So...that's where I'm at. If someone wants to toss me a link to the release candidate code I'll go through the rest of the upgrade and see what if anything falls out...

Cheers!

**Comment by raysmithtx** [comment]
As a beta tester I decided to completely blow up my original install. I reformatted the SD card and started over. The only Arduino experience I have is with the first Raspberry Pints version.

I got the RPints system installed but cannot get to localhost/Phpmyadmin. I know it's installed and there is a /usr/share/phpmyadmin folder. I tried adding the link from day_trippr suggestion of $ cd /var/www
$ ls -s /usr/share/phpmyadmin
It still doesn't work.

I had the exact same problem when I was following the Upgrade documentation too.

That's one of the reasons I decided to blow up the original and start over but apparently there is an issue here since day_trippr had the same problem.

Another small issue is that when I reboot and login it does not auto start. I have to enter startx in order to get RP to load. 

Suggestions?

I

**Comment by Boombrewer** [comment]
localhost/phpmyadmin is case sensitive.  So if you capitalize anything, it will give you a 404 error.  At least on my RPi, its all lowercase.  I had a similar problem when I first started using phpmyadmin.  I think someone might have been writing it phpMyAdmin or phpMyadmin and I couldn't get it to load.

**Comment by mcangeli** [comment]
Boombrewer is correct. It's lower case.

It also sounds like you missed the part where you configure x to start
automatically

At the command line type sudo raspiconfig

(I think that's it, typing from memory)

Somewhere in there is the place to configure x to start on boot.

**Comment by raysmithtx** [comment]
I was/am using all lowercase and I still get the error "The requested URL /phpmyadmin was not found on this server/"

**Comment by Skemp45** [comment]
Thats because its actually
`ln -s /usr/share/phpMyAdmin phpmyadmin`

This will make a symbolic link to the phpmyadmin folder and be callable by ip/phpmyadmin

**Comment by raysmithtx** [comment]
Tried that. No luck. Tried reinstalling phpmyadmin and get the message that phpmyadmin is already the newest version. So apparently it's there, I just cant seem to get to it.

**Comment by Skemp45** [comment]
try this, 
`vim /etc/httpd/conf.d/phpMyAdmin.conf`
changethe Allow and Deny in the first directory tag to Deny from None and then allow from All
<Directory /usr/share/phpMyAdmin/>
 <IfModule mod_authz_core.c>
     # Apache 2.4
     <RequireAny>
       Require ip 127.0.0.1
       Require ip ::1
     </RequireAny>
   </IfModule>
   <IfModule !mod_authz_core.c>
     # Apache 2.2
     Order Deny,Allow
     Deny from None
     Allow from All
     Allow from ::1
 </IfModule>
</Directory>

**Comment by Skemp45** [comment]
Then do a `service httpd restart`

**Comment by Skemp45** [comment]
That should fix it

**Comment by Skemp45** [comment]
![howtophpmyadmin](https://cloud.githubusercontent.com/assets/6318869/4048322/43172f62-2d42-11e4-92f8-0def6ae6f5a5.png)

**Comment by Skemp45** [comment]
http://raspberrypints.com/build-upgrade/

I made some updates to the beginning of the article when it comes to phpmyadmin. let me know if it looks good

**Comment by raysmithtx** [comment]
When I try the vim command I get an error 'bash: vim command not found'. I tried to edit the file with sudo nano but got an error there too. I used the file manager and looked and there is no httpd subdirectory inside the /etc/ directory that I can see. What am I missing? Trying not to be stupid but at this point it can't be helped.

**Comment by Skemp45** [comment]
try sudo yum nano to make sure nano is installed

**Comment by day-trippr** [comment]
Latest changes to the upgrade procedure look good!
Ready for launch!

Cheers!

**Comment by mcangeli** [comment]
It's in /etc/apache2

At this point you might be better to reformat and reinstall from scratch.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: raysmithtx notifications@github.com </div><div>Date:08/26/2014  2:14 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Any issues? (#280) </div><div>
</div>When I try the vim command I get an error 'bash: vim command not found'. I tried to edit the file with sudo nano but got an error there too. I used the file manager and looked and there is no httpd subdirectory inside the /etc/ directory that I can see. What am I missing? Trying not to be stupid but at this point it can't be helped.

**Comment by raysmithtx** [comment]
i know sudo nano works because that's what I used to make the changes during the installation.
There is a conf.d directory in the /etc/apache2/  but no phpmyadmin file there.

**Comment by Skemp45** [comment]
I would follow what @mcangeli  said

**Comment by Skemp45** [comment]
F'in A team F'in A, fine work this release. way to pull it together and prepare a release from a 6 month sabbatical ;)
